"""Render the de-personalized "Automated PR Review" agent from principles.md.

Same splice pattern as build_agent.py, but strips the OHF/Sage framing and all maintainer names
so the reviewer presents everything as the project's own coding standards.
"""
import re
import sys
from pathlib import Path

START = "<!-- PRINCIPLES:START -->"
END = "<!-- PRINCIPLES:END -->"

_NAMES = re.compile(r"Marcel|Marvin|marcelveldt|MarvinSchenkel|OHF Sage|\bSage\b")


def depersonalize(text):
    """Drop the OHF/Sage framing and every maintainer name from the principles body."""
    lines = []
    for raw in text.splitlines():
        if raw.startswith("# OHF"):
            continue  # title comes from the template
        if "Generated by the OHF Principles Advisor" in raw:
            continue  # drop the synthesis/mining provenance blurb
        line = raw.replace("## Overall (Marcel — marcelveldt)", "## General standards")
        line = line.replace(
            "## Music Assistant (Marvin — MarvinSchenkel & MA maintainers)",
            "## Music Assistant standards",
        )
        if "drawn from Marcel's review comments" in line:
            line = "Cross-project engineering standards that apply regardless of which repo is in play."
        lines.append(line)
    body = "\n".join(lines).strip("\n")
    residual = sorted(set(_NAMES.findall(body)))
    if residual:
        raise ValueError(f"de-personalization missed: {residual}")
    return body


def build(template_path, principles_path, out_path):
    """Splice the de-personalized standards into the review-bot template."""
    template = Path(template_path).read_text(encoding="utf-8")
    if START not in template or END not in template:
        raise ValueError("template missing PRINCIPLES markers")
    body = depersonalize(Path(principles_path).read_text(encoding="utf-8"))
    pre = template.split(START)[0]
    post = template.split(END)[1]
    result = f"{pre}{START}\n{body}\n{END}{post}"
    Path(out_path).write_text(result, encoding="utf-8")
    return result


def main(argv=None):
    argv = argv or sys.argv[1:]
    root = Path(__file__).resolve().parents[1]
    template = argv[0] if len(argv) > 0 else root / "agent/review-bot.template.md"
    principles = argv[1] if len(argv) > 1 else root / "principles/principles.md"
    out = argv[2] if len(argv) > 2 else root / "agent/music-assistant-review-bot.md"
    build(template, principles, out)
    print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
